(define (square x) (* x x))
(define (sumOfSquare a b) (+ (square a) (square b)))
(define (sumOfLargerSquares x y z)
  (cond ((and (< x y) (< x z)) (sumOfSquare y z))
        ((and (< x y) (> x z)) (sumOfSquare x y))
        (else (sumOfSquare x y))))